// instruments.js
// Auto-generated by Strudel to ZzFXM
// Last updated: 2026-01-23T22:59:23.155Z
//
// Waveform Indexes (Index 6):
// 0: Sine
// 1: Triangle
// 2: Sawtooth
// 3: Tangent
// 4: Noise
// 5: Square (Pulse)

export const zzfxm_test_hh = [1,0.05,934,0.02,0.02,0.03,4,2.6,11,0,-296,0.67,0,0,0,0,0.16,0.51,0.01,0.26,0];
export const zzfxm_test_cp = [1,0,110,0.55,1.4,3,1,11,0,0,0,0,0,0.45,0,0,0.9,0.21,0,0,-2964];
export const zzfxm_test_blip = [0.5,0.05,523.2511,0.01,0.06,0.3,0,1,0,0,0,0,0,0,0,0,0,0.52,0.02,0,0];
export const zzfxm_test_blur = [0.5,0.05,215,0,0.04,0.01,4,0.3,0,15,133,0.38,0.04,0,0,0,0,0.72,0.2,0,278];
export const zzfxm_test_flute = [1,0,523.2511,0.14,1,1,1,1,0,0,0,0,0,0.1,0,0,0.25,0,0.08,0,0];
export const zzfxm_test_sine = [0.2,0,220,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_tri = [0.2,0,220,0.01,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_saw = [0.2,0,220,0.01,0,0,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_tan = [0.2,0,220,0.01,0,0,3,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_minimal = [0.1,6,220,0.2,3,1,0,20,-1,1,155,10,1,0,5,0,0.3,0.1,1,1,-500];
export const zzfxm_test_noise = [0.2,0,220,0.01,0,0,4,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_square = [0.2,0,220,0.01,0,0,5,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_kick = [1,0,72,0,0.01,0.08,0,1,0,0,0,0,0,0,0,0,0,0.57,0.01,0,0];
export const zzfxm_demo_clap = [1.3,0.05,240,0,0.01,0.28,4,1.4,38,98,477,0,0,0,172,0,0,0.4,0.03,0,-1203];
export const zzfxm_demo_lead = [0.5,0,440,0.01,0,0,1,3,0,0,0,0,2,0.4,0,0,0.625,0,0.5,3,-720];
export const zzfxm_demo_pad = [0.2,0,440,0.5,1,0,2,3,0,0,0,0,0.4,0.2,0,0,0,0.2,0.4,0.3,-553];
export const zzfxm_demo_bass = [0.4,0,440,0.01,0,0,5,1,0,0,0,0,0,0,0,0,0,0,0.3,0,-555];
export const zzfxm_demo_kickdrum = [1,0,130,0,0.08,0.05,1,0.5,-2,5,0,0,0,0,0,0,0,0.3,0.1,0,0];

/**
 * Strudel Sound Names to ZzFXM Channel Indices
 * This mapping ensures we can use descriptive names in Strudel
 * while still baking to correct ZzFXM channels.
 */
export const instrumentMapping = {
    "test-hh": 0,
    "test-cp": 1,
    "test-blip": 2,
    "test-blur": 3,
    "test-flute": 4,
    "test-sine": 5,
    "test-tri": 6,
    "test-saw": 7,
    "test-tan": 8,
    "test-minimal": 9,
    "test-noise": 10,
    "test-square": 11,
    "test-kick": 12,
    "demo-clap": 13,
    "demo-lead": 14,
    "demo-pad": 15,
    "demo-bass": 16,
    "demo-kickdrum": 17
};

// Map them to IDs you want to use in Strudel
export const instruments = {
    "test-hh": zzfxm_test_hh,
    "test-cp": zzfxm_test_cp,
    "test-blip": zzfxm_test_blip,
    "test-blur": zzfxm_test_blur,
    "test-flute": zzfxm_test_flute,
    "test-sine": zzfxm_test_sine,
    "test-tri": zzfxm_test_tri,
    "test-saw": zzfxm_test_saw,
    "test-tan": zzfxm_test_tan,
    "test-minimal": zzfxm_test_minimal,
    "test-noise": zzfxm_test_noise,
    "test-square": zzfxm_test_square,
    "test-kick": zzfxm_test_kick,
    "demo-clap": zzfxm_demo_clap,
    "demo-lead": zzfxm_demo_lead,
    "demo-pad": zzfxm_demo_pad,
    "demo-bass": zzfxm_demo_bass,
    "demo-kickdrum": zzfxm_demo_kickdrum
};

// Also export as array for the baker (ordered by channel index)
export const instrumentArray = [
    zzfxm_test_hh,
    zzfxm_test_cp,
    zzfxm_test_blip,
    zzfxm_test_blur,
    zzfxm_test_flute,
    zzfxm_test_sine,
    zzfxm_test_tri,
    zzfxm_test_saw,
    zzfxm_test_tan,
    zzfxm_test_minimal,
    zzfxm_test_noise,
    zzfxm_test_square,
    zzfxm_test_kick,
    zzfxm_demo_clap,
    zzfxm_demo_lead,
    zzfxm_demo_pad,
    zzfxm_demo_bass,
    zzfxm_demo_kickdrum
];
