// instruments.js
// Auto-generated by Strudel to ZzFXM
// Last updated: 2026-01-23T19:28:58.230Z
//
// Waveform Indexes (Index 6):
// 0: Sine
// 1: Triangle
// 2: Sawtooth
// 3: Tangent
// 4: Noise
// 5: Square (Pulse)

export const INST_LEAD = [1,0.05,88,0.01,0.04,0.01,4,0.5,-2,-1,455,0.42,0,0,362,0,0,0.86,0,0,-1380];
export const INST_HH = [1,0.05,934,0.02,0.02,0.03,4,2.6,11,0,-296,0.67,0,0,0,0,0.16,0.51,0.01,0.26,0];
export const INST_CP = [1,0,110,0.55,1.4,3,1,11,0,0,0,0,0,0.45,0,0,0.9,0.21,0,0,-2964];
export const INST_BLIP = [0.5,0.05,523.2511,0.01,0.06,0.3,0,1,0,0,0,0,0,0,0,0,0,0.52,0.02,0,0];
export const INST_BLUR = [0.5,0.05,215,0,0.04,0.01,4,0.3,0,15,133,0.38,0.04,0,0,0,0,0.72,0.2,0,278];
export const zzfxm_test_flutepad = [1,0,523.2511,0.14,1,1,1,1,0,0,0,0,0,0.1,0,0,0.25,0,0.08,0,0];
export const INST_SINE = [0.2,0,220,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_TRI = [0.2,0,220,0.01,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_SAW = [0.2,0,220,0.01,0,0,2,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_TAN = [0.2,0,220,0.01,0,0,3,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_NOISE = [0.2,0,220,0.01,0,0,4,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_SQUARE = [1,0,220.6,0.01,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_NEW_TEST = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const INST_MINIMAL = [0.1,6,220,0.2,3,1,0,20,-1,1,155,10,1,0,5,0,0.3,0.1,1,1,-500];
export const INST_TEST_BASS = [80.2,0,110440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_my_migrated_bass = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_new_name = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_bass = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_foo = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_renamed_fart = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_ghost_test_2 = [0.2,0,440,0.01,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_kick = [1,0,68,0,0.01,0.08,0,1,0,0,0,0,0,1.2,0,0,0,0.58,0.01,0,0];
export const zzfxm_test_lead = [0.5,0,440,0.01,0.45,0.2,1,2,0,0,0,0,0,0,0,0,0,0.26,1,0,-920];
export const zzfxm_test_clap = [0.2,0,440,0.01,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0];
export const zzfxm_test_clap2 = [.5,.05,140,0,.02,.28,3,1.4,30,98,477,0,0,1,172,0,0,.9,.13,0,-1403];
/**
 * Strudel Sound Names to ZzFXM Channel Indices
 * This mapping ensures we can use descriptive names in Strudel
 * while still baking to correct ZzFXM channels.
 */
export const instrumentMapping = {
    "z-lead": 0,
    "z-hh": 1,
    "z-cp": 2,
    "z-blip": 3,
    "z-blur": 4,
    "test-flutepad": 5,
    "z-sine": 6,
    "z-tri": 7,
    "z-saw": 8,
    "z-tan": 9,
    "z-noise": 10,
    "z-square": 11,
    "z-new-test": 12,
    "z-minimal": 13,
    "z-test-bass": 14,
    "my-migrated-bass": 15,
    "new-name": 16,
    "bass": 17,
    "foo": 18,
    "renamed-fart": 19,
    "ghost-test-2": 20,
    "test-kick": 21,
    "test-lead": 22,
    "test-clap": 23
};

// Map them to IDs you want to use in Strudel
export const instruments = {
    "z-lead": INST_LEAD,
    "z-hh": INST_HH,
    "z-cp": INST_CP,
    "z-blip": INST_BLIP,
    "z-blur": INST_BLUR,
    "test-flutepad": zzfxm_test_flutepad,
    "z-sine": INST_SINE,
    "z-tri": INST_TRI,
    "z-saw": INST_SAW,
    "z-tan": INST_TAN,
    "z-noise": INST_NOISE,
    "z-square": INST_SQUARE,
    "z-new-test": INST_NEW_TEST,
    "z-minimal": INST_MINIMAL,
    "z-test-bass": INST_TEST_BASS,
    "my-migrated-bass": zzfxm_my_migrated_bass,
    "new-name": zzfxm_new_name,
    "bass": zzfxm_bass,
    "foo": zzfxm_foo,
    "renamed-fart": zzfxm_renamed_fart,
    "ghost-test-2": zzfxm_ghost_test_2,
    "test-kick": zzfxm_test_kick,
    "test-lead": zzfxm_test_lead,
    "test-clap": zzfxm_test_clap
};

// Also export as array for the baker (ordered by channel index)
export const instrumentArray = [
    INST_LEAD,
    INST_HH,
    INST_CP,
    INST_BLIP,
    INST_BLUR,
    zzfxm_test_flutepad,
    INST_SINE,
    INST_TRI,
    INST_SAW,
    INST_TAN,
    INST_NOISE,
    INST_SQUARE,
    INST_NEW_TEST,
    INST_MINIMAL,
    INST_TEST_BASS,
    zzfxm_my_migrated_bass,
    zzfxm_new_name,
    zzfxm_bass,
    zzfxm_foo,
    zzfxm_renamed_fart,
    zzfxm_ghost_test_2,
    zzfxm_test_kick,
    zzfxm_test_lead,
    zzfxm_test_clap
];
