/**
 * Module: features/playback/export-preview
 * Purpose: Exported song preview rendering and JSON/JS preview modal controls.
 */

let deps = {
    getDom: () => ({}),
    getLastExportedData: () => null,
    getLastExportedMeta: () => null,
    getLastExportedContext: () => ({ type: null, filename: null }),
    getCurrentPatternFilename: () => null,
    getCurrentArrangementFilename: () => null,
    getPlaybackMixSettings: () => ({}),
    getAudioContext: () => null,
    stopAllPlaybackForSelectionChange: () => {},
    playZzfxmSong: () => {},
    stopZzfxmSong: () => {},
    triggerFileDownload: () => {},
    setStatus: () => {},
    getIsPreviewPlaying: () => false,
    setIsPreviewPlaying: () => {},
    createIcons: () => {},
    icons: {},
};

let songDataViewMode = 'json';

export function configureExportPreview(options = {}) {
    deps = { ...deps, ...options };
}

export function buildZzfxmSongJsModule(songData) {
    const headerLines = [
        '//! Generated by ZzFXTrack',
        '// ZzFXTrack Player song data: [instruments, patterns, sequence, BPM]',
        '',
    ];
    const json = JSON.stringify(songData);
    return `${headerLines.join('\n')}export const songData = ${json};\nexport default songData;\n`;
}

export function renderSongDataPreview() {
    const dom = deps.getDom();
    const lastExportedData = deps.getLastExportedData();
    if (!lastExportedData || !dom.previewJson) return;
    if (songDataViewMode === 'js') {
        dom.previewJson.innerText = buildZzfxmSongJsModule(lastExportedData);
    } else {
        dom.previewJson.innerText = JSON.stringify(lastExportedData, null, 2);
    }
}

function setSongDataViewMode(mode) {
    const dom = deps.getDom();
    if (mode !== 'json' && mode !== 'js') return;
    songDataViewMode = mode;
    if (dom.songDataJsonTab) {
        dom.songDataJsonTab.classList.toggle('active', mode === 'json');
    }
    if (dom.songDataJsTab) {
        dom.songDataJsTab.classList.toggle('active', mode === 'js');
    }
    if (deps.getLastExportedData()) {
        renderSongDataPreview();
    }
}

export function updatePreviewPlayButton(playing) {
    const dom = deps.getDom();
    deps.setIsPreviewPlaying(playing);
    dom.previewPlayBtn.dataset.previewPlaying = playing ? 'true' : 'false';
    dom.previewPlayBtn.innerHTML = playing
        ? '<i data-lucide="square" class="w-4 h-4 fill-current"></i>'
        : '<i data-lucide="play" class="w-4 h-4 fill-current"></i>';
    deps.createIcons({ icons: deps.icons });
}

function openJsonModal() {
    const dom = deps.getDom();
    setSongDataViewMode(songDataViewMode || 'json');
    dom.jsonPreviewModal.classList.add('open');
}

function closeJsonModal() {
    const dom = deps.getDom();
    dom.jsonPreviewModal.classList.remove('open');
}

async function copyJsonToClipboard() {
    const dom = deps.getDom();
    const text = dom.previewJson.innerText;
    if (!text) return;
    try {
        await navigator.clipboard.writeText(text);
        const originalText = dom.copyJsonBtn.innerText;
        dom.copyJsonBtn.innerText = 'Copied!';
        dom.copyJsonBtn.disabled = true;
        setTimeout(() => {
            dom.copyJsonBtn.innerText = originalText;
            dom.copyJsonBtn.disabled = false;
        }, 2000);
    } catch (err) {
        deps.setStatus('Failed to copy to clipboard', 'error');
    }
}

function downloadJsonData() {
    const dom = deps.getDom();
    const text = dom.previewJson?.innerText || '';
    if (!text || !text.trim()) {
        deps.setStatus('No exported data to download.', 'error');
        return;
    }
    const contextFilename = deps.getLastExportedContext()?.filename
        || deps.getCurrentPatternFilename()
        || deps.getCurrentArrangementFilename()
        || null;
    const baseName = contextFilename ? contextFilename.replace(/\.(js|json)$/i, '') : 'pattern-data';
    const isJs = songDataViewMode === 'js';
    const filename = isJs ? `${baseName}.js` : `${baseName}.json`;
    const mime = isJs ? 'application/javascript;charset=utf-8' : 'application/json;charset=utf-8';
    deps.triggerFileDownload(filename, text, mime);
    deps.setStatus(`Downloaded ${filename}`, 'success');
}

export function installExportPreviewHandlers() {
    const dom = deps.getDom();
    dom.previewPlayBtn.addEventListener('click', () => {
        if (deps.getIsPreviewPlaying()) {
            deps.stopZzfxmSong();
            updatePreviewPlayButton(false);
            return;
        }
        const lastExportedData = deps.getLastExportedData();
        if (!lastExportedData) {
            deps.setStatus('Nothing to play. Export ZzFXTrack first.', 'error');
            return;
        }
        deps.stopAllPlaybackForSelectionChange();
        deps.playZzfxmSong(lastExportedData, deps.getAudioContext(), () => {
            updatePreviewPlayButton(false);
        }, { ...(deps.getLastExportedMeta() || {}), ...deps.getPlaybackMixSettings() });
        updatePreviewPlayButton(true);
    });

    if (dom.showJsonBtn) dom.showJsonBtn.addEventListener('click', openJsonModal);
    if (dom.closeJsonModalBtn) dom.closeJsonModalBtn.addEventListener('click', closeJsonModal);
    if (dom.closeJsonModalBottomBtn) dom.closeJsonModalBottomBtn.addEventListener('click', closeJsonModal);
    if (dom.downloadJsonBtn) dom.downloadJsonBtn.addEventListener('click', downloadJsonData);
    if (dom.copyJsonBtn) dom.copyJsonBtn.addEventListener('click', copyJsonToClipboard);
    if (dom.songDataJsonTab) dom.songDataJsonTab.addEventListener('click', () => setSongDataViewMode('json'));
    if (dom.songDataJsTab) dom.songDataJsTab.addEventListener('click', () => setSongDataViewMode('js'));
}
